plot4 <- function() {
	data <- read.table("household_power_consumption.txt", header=TRUE, sep=';', nrows=70000)
	data_subset <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
	gap <- as.numeric(as.character(data_subset$Global_active_power))
	esm1 <- as.numeric(as.character(data_subset$Sub_metering_1))
	esm2 <- as.numeric(as.character(data_subset$Sub_metering_2))
	esm3 <- as.numeric(as.character(data_subset$Sub_metering_3))
	volt <- as.numeric(as.character(data_subset$Voltage))
	grp <- as.numeric(as.character(data_subset$Global_reactive_power))
	datetime <- strptime(paste(data_subset$Date, data_subset$Time), "%d/%m/%Y %H:%M:%S")
	par(mfcol=c(2,2))
	plot(datetime, gap, type="l", xlab="", ylab="Global Active Power")
	plot(datetime, esm1, type="l", col="black", xlab="", ylab="Energy sub metering")
	lines(datetime, esm2, col="red")
	lines(datetime, esm3, col="blue")
	legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.75, bty="n")
	plot(datetime, volt, type="l", ylab="Voltage")
	plot(datetime, grp, type="l", ylab="Global_reactive_power")
	dev.copy(png, file="plot4.png")
	dev.off()
}